<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="3">

  <testsuite name="meritnation"
    errors="1" failures="0" hostname="" id="" package="meritnation" skipped="2"
    tests="3" time="0.01500" timestamp="Sun, 07 May 2017 18:28:14 GMT">
  
    <testcase name="User Logs in" classname="meritnation" time="0.01500" assertions="0">
    </testcase>
      <system-err>
          Error while running [Meritnation / User Logs in]:

  TypeError: login.goToMeritnation is not a function
    at Object.UserLogsIn [as User Logs in] (C:/Users/dsood/Desktop/nightwatch/tests/meritnation.js:8:11)
    at Module.call (C:\Users\dsood\Desktop\nightwatch\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\dsood\Desktop\nightwatch\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\dsood\Desktop\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\dsood\Desktop\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\dsood\Desktop\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\dsood\Desktop\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\dsood\Desktop\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\dsood\Desktop\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
      </system-err>
  
  
    
    <testcase
      name="User enter username and password" classname="meritnation">
      <skipped />
    </testcase>
    
    <testcase
      name="Verify User" classname="meritnation">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
